api_version: 1
threadsafe: true
application: navetteas
version: 1
runtime: python27

default_expiration: "1d"

handlers:
# Manifest files

- url: /(.+\.(appcache|manifest))
  static_files: \1
  upload: static/(.+\.(appcache|manifest))
  mime_type: text/cache-manifest
  expiration: "0s"

- url: /(.+\.webapp)
  static_files: \1
  upload: (.+\.webapp)
  mime_type: application/x-web-app-manifest+json
  expiration: "0s"

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /files
  static_dir: files

- url: /bower_components
  static_dir: bower_components

- url: .*
  script: main.app

libraries:
  - name: jinja2
    version: latest
  - name: webapp2
    version: latest
